apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: {{ .Values.clusterName }}
  namespace: openshift-machine-api
spec:
  replicas: 3
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: {{ .Values.clusterName }}
      machine.openshift.io/cluster-api-machineset: {{ .Values.clusterName }}-infra
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: {{ .Values.clusterName }}
        machine.openshift.io/cluster-api-machine-role: infra
        machine.openshift.io/cluster-api-machine-type: infra
        machine.openshift.io/cluster-api-machineset: {{ .Values.clusterName }}-infra
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/infra: "" 
      taints: 
        - key: node-role.kubernetes.io/infra
          effect: NoSchedule
      providerSpec:
        value:
          numCoresPerSocket: {{ default 4 .Values.machine.numCPUs }}
          diskGiB: {{ default 120 .Values.machine.diskGiB }}
          snapshot: ''
          userDataSecret:
            name: worker-user-data
          memoryMiB: {{ default 8192 .Values.machine.memoryMiB }}
          credentialsSecret:
            name: {{ default vsphere-cloud-credentials .Values.clusterProvider.redentials}}
          network:
            devices:
              - networkName: {{ .Values.vmware.networkName }}
          numCPUs: {{ default 4 .Values.machine.numCPUs }}
          kind: VSphereMachineProviderSpec
          workspace:
            datacenter: {{ .Values.vmware.datacenter }}
            datastore: {{ .Values.vmware.datastore }}
            folder: {{ .Values.vmware.folder }}
            resourcePool: {{ .Values.vmware.resourcePool }}
            server: {{ .Values.vmware.vcenterServer }}
          template: {{ .Values.machine.templateName }}
          apiVersion: vsphereprovider.openshift.io/v1beta1


